### ISSUE TITLE
Using the app changes visibility of labels in gmail

### ISSUE THREAD

**Issue by erikus** [ojanvafai/make-time#48] opened 2019-01-11 21:57 UTC
After using maketime I noticed some new gmail labels (that's fine) and that they are set to visible in the label list (possibly fine). When I changed them to hidden and reloaded the app they were changed back to being visible. I also noticed some other previously hidden labels are now visible.

**Comment by ojanvafai** [comment] 2019-01-11 22:05
It shouldn't affect visibility of any labels other that mt prefixed ones. So, that's definitely a bug. Labels.updateLabelVisibility_ currently checks that a label is a user label, but it actually should be checking that a label is a maketime label. This should just be a one line change of Labels.isUserLabel(label.id) --> Labels.isMakeTimeLabel(label.name) in updateLabelVisibility_.

It's intended behavior that it resets visibility of the mt labels on each load mainly because it let's us change the default visibility of labels as we decide maketime should behave differently. Open to suggestions on the right way to handle this. I guess we could only set the label visibility when we first create the label, but then we lose the ability to decide that some labels really should or shoudn't be hidden in the future.

**Comment by ojanvafai** [comment] 2019-01-12 05:31
It's at least fixed now to not mess with non-maketime labels. I think the solution for maketime labels might be to actually expose control over the visibility of those labels in maketime settings. The majority of that would just be figuring out what the UI of it should be. The application logic for this is very easy.

**Comment by erikus** [comment] 2019-01-12 06:06
Thanks for fixing the non-maketime label visibility issue!

As for the maketime visibility options, why not use your first suggestion of setting it the first time and letting users control it themselves in gmail afterward? It seems like unnecessary work to expose settings and manage it in maketime.

**Closed** 2019-01-12 17:33 UTC
